export const ERROR_VALUE_FORM_SETTINGS_CONTEST = 'ALERTS/ERROR_VALUE_FORM_SETTINGS_CONTEST'

export const CLOSE_ACTIVE_ALERT = 'ALERTS/CLOSE_ACTIVE_ALERT'

export const SET_SNACKBAR_SETTING = 'ALERTS/SET_SNACKBAR_SETTING'
