export const SET_SOURCE = 'ANALYTICS/SET_SOURCE'
export const SET_DEVICE = 'ANALYTICS/SET_DEVICE'

export const SET_ANALYTICS_CONTEST = 'ANALYTICS/SET_ANALYTICS_CONTEST'
export const SET_ANALYTICS_PERIOD_CONTEST = 'ANALYTICS/SET_ANALYTICS_PERIOD_CONTEST'
export const SET_ANALYTICS_BY_CONDITION = 'ANALYTICS/SET_ANALYTICS_BY_CONDITION'
