export const UPDATE_DATA_CONNECTED_GROUPS = 'DATA_GROUPS/UPDATE_DATA_CONNECTED_GROUPS';
export const UPDATE_DATA_GROUPS_TO_CONNECT = 'DATA_GROUPS/UPDATE_DATA_GROUPS_TO_CONNECT';
export const SET_ACTIVE_GROUP = 'DATA_GROUPS/SET_ACTIVE_GROUP'
export const ADD_GROUP_TO_CONNECTED = 'DATA_GROUPS/ADD_GROUP_TO_CONNECTED'
export const DELETE_GROUP_TO_CONNECT = 'DATA_GROUPS/DELETE_GROUP_TO_CONNECT'

export const SET_VALUE_PAID_CONTESTS = 'DATA_GROUPS/SET_VALUE_PAID_CONTESTS'
