export const SET_ID_ACTIVE_CONTEST = 'DATA_CONTESTS/SET_ID_ACTIVE_CONTEST'
export const SET_ID_ACTIVE_TOPIC = 'DATA_CONTESTS/SET_ID_ACTIVE_TOPIC'

export const SET_DATA_ACTIVE_CONTEST = 'DATA_CONTESTS/SET_DATA_ACTIVE_CONTEST'
export const SET_DATA_POPULAR_CONTESTS = 'DATA_CONTESTS/SET_DATA_POPULAR_CONTESTS'

export const SET_CONDITIONS_STATUSES = 'DATA_CONTESTS/SET_CONDITIONS_STATUSES'
export const UPGRADE_CONDITION_STATUS = 'DATA_CONTESTS/UPGRADE_CONDITION_STATUS'
export const RESET_CONDITIONS_STATUSES = 'DATA_CONTESTS/RESET_CONDITIONS_STATUSES'

export const RESET_DATA_ACTIVE_CONTEST = 'DATA_CONTESTS/RESET_DATA_CONTESTS'
export const RESET_ID_ACTIVE_CONTEST = 'DATA_CONTESTS/RESET_ID_ACTIVE_CONTEST'

export const SET_ABRIDGED_DATA_CONTESTS = 'DATA_CONTESTS/SET_SMALL_DATA_CONTESTS'
export const RESET_ABRIDGED_DATA_CONTESTS = 'DATA_CONTESTS/RESET_ABRIDGED_DATA_CONTESTS'

export const SET_IDS_TOPICS_WITH_CONTESTS = 'DATA_CONTESTS/SET_IDS_TOPICS_WITH_CONTESTS'
export const RESET_IDS_TOPICS_WITH_CONTESTS = 'DATA_CONTESTS/RESET_IDS_TOPICS_WITH_CONTESTS'

export const SET_DATA_PARTICIPANTS = 'DATA_CONTESTS/SET_DATA_PARTICIPANTS'
export const RESET_DATA_PARTICIPANTS = 'DATA_CONTESTS/RESET_DATA_PARTICIPANTS'

export const SET_COUNT_PARTICIPANTS = 'DATA_CONTESTS/SET_COUNT_PARTICIPANTS'

export const SET_PAGE_PARTICIPANTS = 'DATA_CONTESTS/SET_PAGE_PARTICIPANTS'
