export const ERROR_INIT_USER = "ERRORS/ERROR_INIT_USER";
export const ERROR_GET_DATA_GROUPS_TO_CONNECT = 'ERRORS/ERROR_GET_DATA_GROUPS_TO_CONNECT'
export const ERROR_GET_DATA_CONTEST = 'ERRORS/ERROR_GET_DATA_CONTEST'

export const SET_ERROR_GET_DATA_CONTESTS = 'ERRORS/ERROR_GET_DATA_CONTESTS'
export const RESET_ERROR_GET_DATA_CONTESTS = 'ERRORS/RESET_ERROR_GET_DATA_CONTESTS'

export const SET_ERROR_GET_DATA_CONNECTED_GROUPS = 'ERRORS/SET_ERROR_GET_DATA_CONNECTED_GROUPS'
export const RESET_ERROR_GET_DATA_CONNECTED_GROUPS = 'ERRORS/RESET_ERROR_GET_DATA_CONNECTED_GROUPS'

export const SET_ERROR_GET_DATA_PARTICIPANTS = 'ERRORS/SET_ERROR_GET_DATA_PARTICIPANT'
export const RESET_ERROR_GET_DATA_PARTICIPANTS = 'ERRORS/RESET_ERROR_GET_DATA_PARTICIPANT'

export const SET_ERROR_PAGE_TOPICS = 'ERRORS/SET_ERROR_PAGE_TOPICS'

export const ERROR_DATA = 'ERRORS/ERROR_DATA'

