export const MAIN_ROUTE = 'ROUTING/MAIN_ROUTE';
export const MODAL_ROUTE = 'ROUTING/MODAL_ROUTE'
export const MODAL_CLOSE = 'ROUTING/MODAL_CLOSE'
export const SET_STATUS_USER = 'ROUTING/SET_STATUS_USER'
export const SET_ROUTING_TO_CONTEST = 'ROUTING/SET_ROUTING_TO_CONTEST'
export const SET_ROUTING_TO_PERSONAL_ACCOUNT = 'ROUTING/SET_ROUTING_TO_PERSONAL_ACCOUNT'

export const SET_ROUTE_TO_BACK = 'ROUTING/SET_ROUT_TO_BACK'
export const GO_BACK = 'ROUTING/GO_BACK'
