export const PAGE_TOPICS = '/'
export const PAGE_CONTESTS_TOPIC = '/contests-topic/'
export const PAGE_PERSONAL_ACCOUNT = '/personal-account'
export const PAGE_CONTEST = '/contest/:id([0-9]+)'
export const PAGE_PARTICIPANTS = '/participants'
export const PAGE_TRAINING_CONTESTS = '/train-contests'
export const PAGE_TRAINING_CONDITIONS = '/train-condition'
export const PAGE_TRAINING_PRIZES = '/train-prizes'

// activeView
export const VIEW_STATUS = 'VIEW_STATUS'
export const VIEW_ORGANIZER = 'VIEW_ORGANIZER'
export const VIEW_PARTICIPANT = 'VIEW_PARTICIPANT'
export const VIEW_CONTEST = 'VIEW_CONTEST'
export const VIEW_SETTINGS_CONTEST = 'VIEW_SETTINGS_CONTEST'
export const VIEW_TRAINING_SECTION = 'TRAINING_SECTION'
export const VIEW_MODERATORS = 'VIEW_MODERATORS'
export const VIEW_BUNG = 'VIEW_BUNG'

// activePanel_status
export const PANEL_SELECTION_STATUS = 'PANEL_SELECTION_STATUS'
// activePanel_organizer
export const PANEL_ORGANIZER_GROUPS = 'PANEL_ORGANIZER_GROUPS'
export const PANEL_CONTESTS_GROUP = 'PANEL_CONTESTS_GROUP'
// activePanel_participant
export const PANEL_TOPICS = 'PANEL_TOPICS'
export const PANEL_CONTESTS_TOPIC = 'PANEL_CONTESTS_TOPIC'
export const PANEL_PERSONAL_ACCOUNT = 'PANEL_PERSONAL_ACCOUNT'
// activePanel_contest
export const PANEL_CONTEST = 'PANEL_CONTEST'
export const PANEL_PARTICIPANTS = 'PANEL_PARTICIPANTS'
export const PANEL_ANALYTIC = 'PANEL_ANALYTIC'
// activePanel_settings
export const PANEL_SETTINGS_CONTEST = 'PANEL_SETTINGS_CONTEST'
export const PANEL_SETTINGS_STORIES = 'PANEL_SETTINGS_STORIES'
export const PANEL_SETTINGS_PUBLIC_WALL = 'PANEL_SETTINGS_PUBLIC_WALL'
export const PANEL_SETTINGS_PREVIEW_CONTEST = 'PANEL_SETTINGS_PREVIEW_CONTEST'
// activePanel_training
export const PANEL_TRAINING_CONTESTS = 'PANEL_TRAINING_CONTESTS'
export const PANEL_TRAINING_CONDITIONS = 'PANEL_TRAINING_CONDITIONS'
export const PANEL_TRAINING_PRIZES = 'PANEL_TRAINING_PRIZES'
// activePanel_moderators
export const PANEL_MODERATORS_GROUPS = 'PANEL_MODERATORS_GROUPS'
// activePanel_bung
export const PANEL_ENGINEERING_WORKS = 'PANEL_ENGINEERING_WORKS'

// activeModalPage
export const MODAL_PAGE_GROUPS_TO_CONNECT = 'MODAL_PAGE_GROUPS_TO_CONNECT'
export const MODAL_PAGE_PRIZES = 'MODAL_PAGE_PRIZES'
export const MODAL_PAGE_WINNERS = 'MODAL_PAGE_WINNERS'
export const MODAL_PAGE_SETTING_CONTEST = 'MODAL_PAGE_SETTING_CONTEST'
export const MODAL_PAGE_SETTING_STORY = 'MODAL_PAGE_SETTING_STORY'
export const MODAL_PAGE_SETTING_PUBLIC_WALL = 'MODAL_PAGE_SETTING_PUBLIC_WALL'
export const MODAL_PAGE_SELECT_COUNTRY = 'MODAL_PAGE_SELECT_COUNTRY'
export const MODAL_PAGE_SELECT_CITY = 'MODAL_PAGE_SELECT_CITY'
