export const { default: Background } = require("./Background/Background")
export const { default: ButtonCustom } = require("./ButtonCustom/ButtonCustom")
export const { default: PlaceholderPage } = require("./PlaceholderPage/PlaceholderPage")
export const { default: ContestCell } = require("./ContestCell/ContestCell")
export const { default: StickerCountParticipants } = require("./StickerCountParticipants/StickerCountParticipants")
export const { default: SelectTopics } = require("./SelectTopics/SelectTopics")
export const { default: PrizeCell } = require("../modals/ModalPrizes/PrizeCell/PrizeCell")
export const { default: StickerEndContest } = require("./StickerEndContest/StickerEndContest")
export const { default: SliderTopContest } = require("./SliderTopContest/SliderTopContest")
export const { default: SmallSpinner } = require("./SmallSpinner/SmallSpinner")
export const { default: UserCell } = require("./UserCell/UserCell")
export const { default: HeaderText } = require("./HeaderText/HeaderText")
export const { default: Markdown } = require("./Markdown/Markdown")

export const { default: LoadingPage } = require("./_pages/LoadingPage/LoadingPage")
export const { default: ErrorPage } = require("./_pages/ErrorPage/ErrorPage")
